### ISSUE TITLE
Cannot read properties of undefined (reading 'uploadSequenceToken')

### ISSUE THREAD

**Issue by ad-m-ss** [rupertbg/aws-load-balancer-logs-to-cloudwatch#5]
Hi,

We have recently started to use the published Lambda function. We noticed that there is an occasional error in the logs for the Lambda function.

```
START RequestId: f0117e89-17ca-4767-b1ff-0d895868934e Version: $LATEST

2022-12-16T09:01:03.186Z f0117e89-17ca-4767-b1ff-0d895868934e INFO Retrieving **CUT**/AWSLogs/672751098944/elasticloadbalancing/us-east-2/2022/12/16/672751098944_elasticloadbalancing_us-east-2_a14108f200b9a4da1a4218924d6a7878_20221216T0900Z_3.22.67.85_i9tc5xm3.log
2022-12-16T09:01:03.884Z f0117e89-17ca-4767-b1ff-0d895868934e INFO Unpacking log data for classic load balancer

2022-12-16T09:01:03.885Z f0117e89-17ca-4767-b1ff-0d895868934e INFO Checking Log Group /aws/elb/**CUT** exists

2022-12-16T09:01:04.026Z f0117e89-17ca-4767-b1ff-0d895868934e INFO Checking Log Streams /aws/elb/**CUT**/2022/12/16/[$LATEST]4d433433cfbe4db1b9afb795e98cb68c

2022-12-16T09:01:04.217Z f0117e89-17ca-4767-b1ff-0d895868934e INFO Creating Log Stream /aws/elb/**CUT**/2022/12/16/[$LATEST]4d433433cfbe4db1b9afb795e98cb68c

2022-12-16T09:01:04.386Z f0117e89-17ca-4767-b1ff-0d895868934e ERROR Invoke Error {"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'uploadSequenceToken')","stack":["TypeError: Cannot read properties of undefined (reading 'uploadSequenceToken')"," at getLogStreamSequenceToken (/var/task/index.js:327:30)"," at processTicksAndRejections (node:internal/process/task_queues:96:5)"," at async Runtime.exports.handler (/var/task/index.js:111:25)"]}

END RequestId: f0117e89-17ca-4767-b1ff-0d895868934e

REPORT RequestId: f0117e89-17ca-4767-b1ff-0d895868934e Duration: 1608.22 ms Billed Duration: 2062 ms Memory Size: 128 MB Max Memory Used: 81 MB Init Duration: 453.23 ms
```

I'm wondering if this is an isolated problem with us or if it's happening to more people.

Kind regards

**Comment by rupertbg** [comment]
Should be fixed in the latest release :)
